accelerator: 'gpu'
random_seed: 0
filter_max_readcount_threshold: 0
filter_max_frequency_threshold: 0.0

wandb.use: True

csv: '/evfi-manuscript-public/datasets/filtzero_without_lastround/Data-C.csv'
genotype_col: 'Genotype'
round_cols: [round_1,round_2,round_3]
project_output_folder: '/evfi-manuscript-public/run-alltime/gt/out/C/deep_latent/'
tsngs.skip_filters: True

# 'train_only' or 'train_and_eval'
stages: 'train_only'
test_split_by_round: False
test_split_by_genotype: False

ft.dataflow: 'string_to_onehot'
ft.alphabet: 'nucleotides'
ft.onehot_len: 12
use_feature_store: False

net.network: 'mlp'
net.mlp_inp_dim: 60
net.mlp_hidden_dim: 256
net.mlp_n_layers: 2
net.mlp_dropout: 0.2
net.mlp_batch_norm: True

dataloader_num_workers: 0
dataloader_persistent_workers: False

simple.epochs: 10000
simple.lr: 0.1
simple.loss_func: 'dirichlet_multinomial'

warmup.val_every_n_epochs: 10
warmup.epochs: 300
warmup.convergence.patience: 30
warmup.lr: 1.0e-4
warmup.weight_decay: 1.0e-4

loss_func: 'dirichlet_multinomial'
epochs: 1000
skip_autobatch: True
e2e.batch_size: 16384
e2e.accumulate_grad: True
e2e.convergence.patience: 50
e2e.val_every_n_epochs: 10
lr: 1.0e-4
weight_decay: 1.0e-4
regularize_logw_weight: 0.0
