lr: 1.0e-3
accelerator: 'gpu'
random_seed: 0

csv: ''
genotype_col: ''
round_cols: []
project_output_folder: ''

loss_func: 'dirichlet_multinomial'

# 'train_only' or 'train_and_eval'
stages: 'train_and_eval'
test_split_by_round: True
train_round_idxs: [0,1,2]
test_round_idxs: [3]
test_split_by_genotype: True
train_genotype_split_percent: 0.8
val_genotype_split_percent: 0.1
test_genotype_split_percent: 0.1

ft.dataflow: 'string_to_tensor'
ft.alphabet: 'amino acids'

net.network: 'transformer'
net.transformer_nhead: 2
net.transformer_num_layers: 1
net.transformer_embed_dim: 4

# for fast dev
simple.epochs: 3
warmup.epochs: 3
epochs: 3
skip_autobatch: True
e2e.batch_size: 16384