accelerator: 'gpu'
random_seed: 0
filter_max_readcount_threshold: 0
filter_max_frequency_threshold: 0.0

wandb.use: True

csv: '/evfi-manuscript-public/datasets/filtzero_without_lastround/Data-F.csv'
genotype_col: 'Genotype'
round_cols: [G0,D1.25,D2.25,D3.25,D4.25]
steps_per_round: [1.25,1,1,1]
project_output_folder: '/evfi-manuscript-public/run-benchmarks/gt/filtzero_without_lastround/out/F/deep_latent/'
tsngs.skip_filters: True
tasks.multinomial.validate_args: False

# 'train_only' or 'train_and_eval'
stages: 'train_and_eval'
test_split_by_round: True
train_round_idxs: [0,1,2]
test_round_idxs: [3]
test_split_by_genotype: False

ft.dataflow: 'string_to_onehot'
ft.alphabet: 'nucleotides'
ft.onehot_len: 29
use_feature_store: False

net.network: 'mlp'
net.mlp_inp_dim: 145
net.mlp_hidden_dim: 256
net.mlp_n_layers: 6
net.mlp_dropout: 0.0
net.mlp_batch_norm: True
warmup.lr: 1.0e-4

dataloader_num_workers: 0
dataloader_persistent_workers: False

simple.epochs: 10000
simple.lr: 0.1

warmup.epochs: 400
warmup.convergence.patience: 30
warmup.val_every_n_epochs: 10
warmup.weight_decay: 1.0e-4

loss_func: 'multinomial'
epochs: 3000
skip_autobatch: True
e2e.val_every_n_epochs: 10
e2e.batch_size: 16384
e2e.accumulate_grad: True
e2e.convergence.patience: 100
lr: 1.0e-4
regularize_logw_weight: 0.0
weight_decay: 1.0e-4